In [79]:
from monty.serialization import MontyDecoder, loadfn
import os
import pprint
from pymatgen.analysis.elasticity.elastic import ElasticTensor
import numpy as np

In [80]:
os.getcwd()

'C:\\Users\\Kory\\Google Drive\\Jupyter_Notebook\\Jarvis'

In [127]:
dat_3d=loadfn('data/jdft_3d-5-23-2018.json',cls=MontyDecoder)
dat_2d=loadfn('data/jdft_2d-5-23-2018.json',cls=MontyDecoder)

In [117]:
print ("#3D materials=",len(dat_3d))
print ("#2D materials=",len(dat_2d))
print ("Available keys",dat_2d[0].keys())
dat_2d[0]['mbj_gap']

#3D materials= 27252
#2D materials= 635
Available keys dict_keys(['magmom', 'fin_en', 'op_gap', 'final_str', 'mpid', 'exfoliation_en', 'elastic', 'incar', 'kpoints', 'mepsz', 'jid', 'mepsx', 'mepsy', 'initial_str', 'form_enp', 'epsx', 'epsy', 'epsz', 'mbj_gap'])


'na'

In [83]:
pprint.pprint(dat_3d[1])

{'eff_mass': {'n': [3.847427511538264e-07,
                    3.847427511538264e-07,
                    3.847427511538264e-07],
              'p': [3.847427511538264e-07,
                    3.847427511538264e-07,
                    3.847427511538264e-07]},
 'elastic': '309.1,159.5,159.5,-0.0,-0.0,0.0,159.5,309.1,159.5,0.0,-0.0,0.0,159.5,159.5,309.1,-0.0,-0.0,0.0,-0.0,0.0,-0.0,145.0,0.0,0.0,-0.0,-0.0,-0.0,0.0,145.0,0.0,0.0,0.0,0.0,0.0,0.0,145.0',
 'encut': 600,
 'epsx': 445.9204,
 'epsy': 445.9204,
 'epsz': 445.9204,
 'fin_en': -14.477249,
 'final_str': Structure Summary
Lattice
    abc : 3.5109611107404795 3.5109611107404795 3.5109611107404795
 angles : 90.0 90.0 90.0
 volume : 43.279083669106654
      A : 3.5109611107404795 0.0 -0.0
      B : -0.0 3.5109611107404795 -0.0
      C : 0.0 0.0 3.5109611107404795
PeriodicSite: Co (1.7555, 1.7555, 0.0000) [0.5000, 0.5000, 0.0000]
PeriodicSite: Co (1.7555, 0.0000, 1.7555) [0.5000, 0.0000, 0.5000]
PeriodicSite: Co (0.0000, 1.7555, 1.7555) 

In [84]:
def get_et(elast_str=''):
    if elast_str == 'na':
        return 'na'
    else:
        cij=np.empty((6, 6), dtype=float)
        elast=np.array(elast_str.split(','),dtype='float')
        count=0
        for ii in range(6):
            for jj in range(6):
                cij[ii][jj]=elast[count]
                count=count+1
        et=ElasticTensor.from_voigt(cij)
        return et
def get_anisotropy(x):
    if x == 'na':
        return 'na'
    else:
        return x.universal_anisotropy

In [87]:
x=get_et(dat_3d[3]['elastic'])
get_anisotropy(x)

c:\users\kory\appdata\local\conda\conda\envs\py3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  from ipykernel import kernelapp as app


24.130578965399071

In [115]:
def get_anisotropy_list(dat_3d, mpid):
    anisotropy_list = []
    for i in dat_3d:
        if i['mpid'] == mpid:
            anisotropy_list.append(get_anisotropy(get_et(i['elastic'])))
            #pprint.pprint(i)
    return anisotropy_list

get_anisotropy_list(dat_3d,dat_2d[0]['mpid'])

c:\users\kory\appdata\local\conda\conda\envs\py3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  from ipykernel import kernelapp as app


['na', 2.7714826212666299]

In [134]:

'mp-1008349' in dat_3d[1].values()


AttributeError: 'list' object has no attribute 'values'

In [78]:
get_et(dat_2d[0]['elastic'])

ElasticTensor([[[[ 63.6  -0.    0. ]
   [ -0.   11.1   0. ]
   [  0.    0.   -0. ]]

  [[ -0.   -0.2  -0. ]
   [ -0.2   0.    0. ]
   [ -0.    0.    0. ]]

  [[  0.   -0.   -0.2]
   [ -0.    0.    0. ]
   [ -0.2   0.    0. ]]]


 [[[ -0.   -0.2  -0. ]
   [ -0.2   0.    0. ]
   [ -0.    0.    0. ]]

  [[ 11.1   0.    0. ]
   [  0.   63.6   0. ]
   [  0.    0.   -0. ]]

  [[  0.    0.    0. ]
   [  0.    0.   24.7]
   [  0.   24.7   0. ]]]


 [[[  0.   -0.   -0.2]
   [ -0.    0.    0. ]
   [ -0.2   0.    0. ]]

  [[  0.    0.    0. ]
   [  0.    0.   24.7]
   [  0.   24.7   0. ]]

  [[ -0.    0.    0. ]
   [  0.   -0.    0. ]
   [  0.    0.   -0.1]]]])

In [48]:
dat_2d[1]

{'magmom': {'magmom_out': -0.0, 'magmom_osz': -0.0},
 'fin_en': -11.70272,
 'op_gap': 0.7467,
 'final_str': Structure Summary
 Lattice
     abc : 3.7013616849136959 4.699616557814899 25.441199999999998
  angles : 90.0 90.0 90.0
  volume : 442.54918198963259
       A : 3.7013616849136959 -0.0 0.0
       B : -0.0 4.699616557814899 0.0
       C : 0.0 0.0 25.441199999999998
 PeriodicSite: As (1.8507, 4.3770, 6.9302) [0.5000, 0.9313, 0.2724]
 PeriodicSite: As (0.0000, 2.6724, 6.9302) [0.0000, 0.5687, 0.2724]
 PeriodicSite: As (1.8507, 0.3226, 4.5110) [0.5000, 0.0687, 0.1773]
 PeriodicSite: As (0.0000, 2.0272, 4.5110) [-0.0000, 0.4313, 0.1773],
 'mpid': 'mp-158',
 'exfoliation_en': 134.86375000000007,
 'elastic': '26.4,8.9,0.0,0.0,0.0,0.0,8.9,8.3,0.1,0.0,0.0,0.0,0.0,0.1,0.1,-0.0,-0.0,0.0,0.0,0.0,-0.0,8.0,0.0,0.0,0.0,0.0,-0.0,0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,-0.0,-0.0',
 'incar': {'LVHAR': True,
  'NELM': 500,
  'IBRION': 2,
  'PARAM2': 0.22,
  'PARAM1': 0.1833333333,
  'LWAVE': False,
  'AGGAC'